  spring:

    liquibase:
      enabled: false
      change-log: db/changelog/master.yaml

    datasource:
#        url: jdbc:postgresql://host.docker.internal:5433/samurai
        url: jdbc:postgresql://localhost:5433/samurai
        username: samurai
        password: password
        driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    docker:
      compose:
        enabled: false
        file: src/main/docker/compose.yml
        lifecycle-management: start_only

  sonar:
    login: admin
    password: NabilHakimi6714@

    jpa:
      properties:
        hibernate:
          default_schema: public

    task:
      scheduling:
        enabled: true

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/hakimi
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  server:
#    ssl:
#      enabled: true
#      key-store: classpath:mykeystore.p12
#      key-store-type: PKCS12
#      key-store-password: mypassword

    port: 8443
