version: '3.8'

name: samurai

services:
  postgres:
    container_name: samurai_db
    image: 'postgres:17'
    environment:
      POSTGRES_DB: samurai
      POSTGRES_USER: samurai
      POSTGRES_PASSWORD: password
    volumes:
      - C:\Users\Youcode\Desktop\data\pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres_data:
    driver: local
